### ISSUE TITLE
Remove return_code from JSON response

### ISSUE THREAD

**Issue by kn9ts** [kn9ts/project-mulla#18]
Should we remove the `return_code` property from the JSON response, it is the one provided by SAG but `project mulla` uses HTTP status codes to represent this in it's REST api

How a response looks like now:

```json
{
    "amountInDoubleFloat": "10.00", 
    "clientPhoneNumber": "0723001575", 
    "cust_msg": "to complete this transaction, enter your bonga pin on your handset. if you don't have one dial *126*5# for instructions", 
    "description": "success", 
    "extraPayload": "{}", 
    "http_code": 200, 
    "merchantTransactionID": "4938a780-1f3b-11e6-acc6-5dabc98661b9", 
    "message": "Transaction carried successfully", 
    "referenceID": "f765b1ef-6890-44f2-bc7a-9be23013da1c", 
    "return_code": "00", 
    "timeStamp": "20160521130337", 
    "trx_id": "6c1b1dcc796ed6c1d5ea6d03d34ddb7f"
}
```

**Comment by habbes** [comment]
Have you mapped all possible return codes to HTTP status codes? If so, then it should be removed so long as its well documented what maps to what.
But  if multiple return codes would map to a single HTTP status codes (for instance in case of errors) then you could include the return_code or an error_code property

**Comment by kn9ts** [comment]
@habbes Besides using HTTP status codes. A JSON body is sent back with the ERROR response

It looks something like this: 

```json
{
  "response": {
    "return_code": "43",
    "http_code": 409,
    "message": "Duplicate merchant transaction ID detected",
    "description": "duplicate merchant transaction id detected",
    "trx_id": "f25ae6f2c1e24ecbb861e40772f2425c"
  }
}
```

**Comment by kn9ts** [comment]
I've decided to keep it. Can be used as a reference code to the documentation if someone wants to do so.
