### ISSUE TITLE
Fix all ESLINT syntax style issues

### ISSUE THREAD

**Issue by kn9ts** [kn9ts/project-mulla#27]
Goto the branch `feature/eslint-airbnb`

Run `npm run lint`

Fix all the issues listed. I am using [AirBNB javascript style guide](https://github.com/airbnb/javascript). Use it for reference if need be.

Download/open the text file attached to find the last known issues. **113** issues I think 😄 

[eslint-issues.txt](https://github.com/kn9ts/project-mulla/files/279075/eslint-issues.txt)

**Comment by denzelwamburu** [comment]
@kn9ts  I can try and take care of it :)

**Comment by kn9ts** [comment]
@denzelwamburu Someone just made a pull request: https://github.com/kn9ts/project-mulla/pull/28

**Comment by denzelwamburu** [comment]
Let me check it out.
