### ISSUE TITLE
Docs: Sample Usage Examples

### ISSUE THREAD

**Issue by andela-anandaa** [kn9ts/project-mulla#32]
A step-by-step walk through with a _practical_ sample usage will be of benefit to those checking out the project -- and will actually drive adoption.

However, good work done here @kn9ts

**Comment by kn9ts** [comment]
@andela-anandaa Thank you. Noted. Been pushing to get it version 1.0.0 so that I can focus with ease on the documentation.

**Comment by kn9ts** [comment]
@andela-anandaa Please find the complete documentation of Project Mulla here: https://kn9ts.github.io/project-mulla
