### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by denzelwamburu** [kn9ts/project-mulla#43]
` HTTP/1.1 500 Internal Server Error`
`Content-Length: 71`
`Content-Type: application/json; charset=utf-8`
`Date: Fri, 10 Jun 2016 19:13:59 GMT`
`ETag: W/"47-QF6qBiKtCUQCLU0A2DNoVg" `
`X-Powered-By: Express`
`set-cookie: connect.sid=s%3ADBjDmYnygsM3- 82Cw9e20F_8at65WasY.sSMgGuVZT0SxTBegG6TVOetY24eo7rp4FVr%2FuGnwOTs; Path=/; HttpOnly`

`{`
    `"response": {`
        `"description": "authentication failed",` 
        `"return_code": "42"`
   ` }`
`}`
Am getting an Authentication error, any way around it?

**Comment by kn9ts** [comment]
@denzelwamburu First of all. The return code has not been mapped to a HTTP status. The Safaricom documentation does not have this error code documented.

Then this might be the `PASSWORD` generated does not validate with the `SAG` endpoint.

**Comment by kn9ts** [comment]
@denzelwamburu Were you able to sort this out?

**Comment by denzelwamburu** [comment]
@kn9ts  Sorry for the late reply. Let me fetch then i try once more.

**Comment by denzelwamburu** [comment]
![screenshot from 2016-06-15 18 55 45](https://cloud.githubusercontent.com/assets/6532631/16087208/e50a07d2-332a-11e6-9742-fcab34c6cce3.png)
Now it's returning a 500 error code.

**Comment by kn9ts** [comment]
@denzelwamburu Am curious. Do you have a `PAYBILL_NO` and `PASSKEY`? Did you get them from Safaricom MPESA API guys?

**Comment by kn9ts** [comment]
Could you please follow these steps: http://kn9ts.github.io/project-mulla/docs/configuration.html

**Comment by denzelwamburu** [comment]
Guess i will close the issue now :smiley:
