### ISSUE TITLE
Different license declarations

### ISSUE THREAD

**Issue by andela-hthuo** [kn9ts/project-mulla#44]
[package.json](https://github.com/kn9ts/project-mulla/blob/master/package.json#L19) declares MIT, [README.md](https://github.com/kn9ts/project-mulla#this-project-uses-gplv3-license) declares GPL-3.0 while [LICENSE](https://github.com/kn9ts/project-mulla/blob/master/LICENSE) contains LGPL-3.0.

**Comment by kn9ts** [comment]
@andela-hthuo Thanks for the heads up. I think that's the one express scaffolding come with. Let me change it.
