### ISSUE TITLE
looking for this fie

### ISSUE THREAD

**Issue by ngethe** [kn9ts/project-mulla#50]
CBInterface_C2BPaymentValidationAndConfirmation.wsdl
please place it here my safaricom contact can't find it

**Comment by kn9ts** [comment]
@ngethe I think you are looking for this file: https://github.com/kn9ts/project-mulla/blob/master/docs/Checkout.wsdl

This API tool does not need it since it uses it's own parser to parse and verify the response payload.

**Comment by ngethe** [comment]
Thanks
