### ISSUE TITLE
not compatible with operating system

### ISSUE THREAD

**Issue by mikekaraa** [kn9ts/project-mulla#53]
Hi I am using windows when I git clone the project it tells me that its not compatible with my operating system and architecture, even though the project is showing in my folder, it did not install successfully.

**Comment by barmao** [comment]
@mikekaraa hello, this is a web service and is not dependent on an operating system. It will require you to set up a local testing enviroment using xampp/wampp or homestead. You will be require to clone this project to the local testing enviroment or on the hosting platform to enable it to work

**Comment by kn9ts** [comment]
@mikekaraa Please make sure you've installed the requirements the tool requires to run seamlessly. Please see here: http://kn9ts.github.io/project-mulla/docs/index.html
