### ISSUE TITLE
testing with curl and httpie

### ISSUE THREAD

**Issue by mikekaraa** [kn9ts/project-mulla#57]
Hi thanks again for this project, i have set up everything however i am having problems testing it with curl or httpie, I am getting many errors in the response, how should I place this in the CMD LINE because it is not working at all
$ curl -i -X POST \
  --url http://localhost:8080/api/v1/payment/request \
  --data 'phoneNumber=254723000000' \
  --data 'totalAmount=10.00' \
  --data 'clientName="Eugene Mutai"' \
  --data 'clientLocation=Kilimani' \

http POST localhost:8080/api/v1/payment/request \
  phoneNumber=254723000000 \
  totalAmount=10.00 \
  clientName='Eugene Mutai' \
  clientLocation='Kilimani'

**Comment by kn9ts** [comment]
@mikekaraa Apologies for the late response. I was on vacation. Could you post the error response?
