### ISSUE TITLE
Support for non-requested payments

### ISSUE THREAD

**Issue by savioabuga** [kn9ts/project-mulla#61]
The current status of the projects seems to allow only payments that are requested for. Are there plans to have payments that are not pulled? The typical payments where one goes to his Mpesa Menu and enters the paybill number and amount.

**Comment by kn9ts** [comment]
That is supported in a different kind of API provided by Safaricom known as C2B interfacing. Basically it pings your server with the details of any payment made to your paybill number that you did not make a PUSH for. @savioabuga
