### ISSUE TITLE
C2B till number

### ISSUE THREAD

**Issue by mikekaraa** [kn9ts/project-mulla#62]
Hi I am using a till number instead of a paybill number, however it is not working when I can confirm the payment, the status code shows 400:10 that 'the phone number is not registered with mpesa' even though it is, what could be the problem

**Comment by kn9ts** [comment]
Could post a sample of how you are submitting the phone number. It may be an issue with Project Mulla or just how you are submitting the numbers @mikekaraa

**Comment by mikekaraa** [comment]
Hi I eventually found out from safcom that its not possible to use a till number for this. Thanks
