### ISSUE TITLE
M-Pesa STK Push Endpoints

### ISSUE THREAD

**Issue by ngethe** [kn9ts/project-mulla#64]
Just got the new M-Pesa STK Push documentation but the endpoints are missing any one with this endpoints??

[M-PESA STK PUSH - Developer Guide - REST- v1.1.pdf](https://github.com/kn9ts/project-mulla/files/536703/M-PESA.STK.PUSH.-.Developer.Guide.-.REST-.v1.1.pdf)

**Comment by kn9ts** [comment]
@ngethe It hasn't been fully released yet. It would be too early to release a working solution for it. Please bare with me. I'm also following it up. Cheers.

**Comment by ngethe** [comment]
Thanks for the feedback an a Million thanks for sharing your Work 
Please share the Endpoint when Out.. Regards

**Comment by kn9ts** [comment]
@ngethe Have you began to use or tested the MPESA STK PUSH API?

**Comment by ngethe** [comment]
No Endpoint for the STK just the document 
are they out?

**Comment by kn9ts** [comment]
Nope it's not. That may take like2 years...hahaha!

**Comment by anthonyosoro** [comment]
I have also been pursuing STK push for like 2 months now. Saf indicates the platform is not yet ready. Try something different like checkout with a service pin. That one is available.

**Comment by nyakambinickson** [comment]
I got the endpoints but they are down

**Comment by ngethe** [comment]
@nyakambinickson this are for USSD based or STK one?

**Comment by nyakambinickson** [comment]
@ngethe I have the STK endpoints for both REST and SOAP but they are still on testbed. Looks like they are not yet ready for production.

**Comment by weddingjuma** [comment]
Hi, on the new mpesa REST API, [https://developer.safaricom.co.ke/apis]

**Comment by weddingjuma** [comment]
Hi, on the new mpesa REST API, (https://developer.safaricom.co.ke/apis)
